### PR TITLE
Use core::str instead of std_unicode::str

### PR DESCRIPTION
**Pull request by FenrirWolf**
Fixes a compilation error introduced by https://github.com/rust-lang/rust/pull/40189

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @FenrirWolf.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a10e1c8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a10e1c8 with merge a10e1c8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/steed/builds/208986539)
Approved by: japaric
Pushing a10e1c82e56c33df5494349d24964e5b5ba4dedd to master...
